imports:
    - { resource: "@OdiseoSyliusVendorPlugin/Resources/config/grids/vendor.yml" }

knp_gaufrette:
    stream_wrapper: ~

vich_uploader:
   db_driver: orm # or mongodb or propel or phpcr
   storage:   gaufrette

   mappings:
        vendor_logo:
            uri_prefix:         /vendor-logo
            upload_destination: sylius_image
            namer:              vich_uploader.namer_uniqid
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true

liip_imagine:
    filter_sets:
        odiseo_sylius_vendor_logo:
            filters:
                thumbnail: { size: [300, 300], mode: inset }
                background: { size: [300, 300], position: center, color: '#FFFFFF' }