parameters:
services:
    #FORM EXTENSIONS
    odiseo_sylius_vendor.form.extension.type.product:
        class: Odiseo\SyliusVendorPlugin\Form\Extension\ProductTypeExtension
        tags:
            - { name: form.type_extension, extended_type: Sylius\Bundle\ProductBundle\Form\Type\ProductType }

    #FORM TYPES
    odiseo_sylius_vendor.form.type.vendor_choice:
        class: Odiseo\SyliusVendorPlugin\Form\Type\VendorChoiceType
        arguments: ["@odiseo_sylius_vendor.repository.vendor"]
        tags:
            - { name: form.type , alias: odiseo_sylius_vendor_choice }

    odiseo_sylius_vendor.form.type.vendor:
        class: Odiseo\SyliusVendorPlugin\Form\Type\VendorType
        arguments: ['%odiseo_sylius_vendor.model.vendor.class%', []]
        tags:
            - { name: form.type, alias: odiseo_sylius_vendor }

    odiseo_sylius_vendor.form.type.vendor_translation:
        class: Odiseo\SyliusVendorPlugin\Form\Type\VendorTranslationType
        arguments: ['%odiseo_sylius_vendor.model.vendor_translation.class%', []]
        tags:
            - { name: form.type, alias: odiseo_sylius_vendor_translation }

    #LISTENERS
    odiseo_sylius_vendor.listener.admin.menu_builder:
        class: Odiseo\SyliusVendorPlugin\Menu\AdminMenuListener
        tags:
            - { name: kernel.event_listener, event: sylius.menu.admin.main, method: addAdminMenuItems }

    odiseo_sylius_vendor.vendor_aware_listener.doctrine.orm:
        class: Odiseo\SyliusVendorPlugin\EventListener\ORMVendorAwareListener
        arguments: ["@sylius.resource_registry", "%odiseo_sylius_vendor.model.vendor.class%", "%sylius.model.product.class%", "%sylius.model.channel.class%"]
        tags:
            - { name: doctrine.event_subscriber, connection: default, priority: 99 }

    #FIXTURES
    odiseo_sylius_vendor.fixture.vendor:
        class: Odiseo\SyliusVendorPlugin\Fixture\VendorFixture
        arguments: ["@odiseo_sylius_vendor.manager.vendor", "@odiseo_sylius_vendor.factory.vendor", "@odiseo_sylius_vendor.repository.vendor", "@sylius.repository.channel", "@sylius.repository.locale"]
        tags:
            - { name: "sylius_fixtures.fixture" }

    #SITEMAPS
    odiseo_sylius_vendor.sitemap_provider.vendor:
        class: Odiseo\SyliusVendorPlugin\SitemapProvider\VendorUrlProvider
        arguments:
            - "@odiseo_sylius_vendor.repository.vendor"
            - "@router"
            - "@sylius.sitemap_url_factory"
            - "@sylius.context.locale"
            - "@sylius.context.channel"
        tags:
            - { name: sylius.sitemap_provider }
