Odiseo\SyliusVendorPlugin\Model\Product:
    type: mappedSuperclass
    table: odiseo_product
    manyToOne:
        vendor:
            targetEntity: Odiseo\SyliusVendorPlugin\Model\VendorInterface
            inversedBy: products
            joinColumn:
                name: vendor_id
                referenceColumnName: id
                onDelete: 'SET NULL'