sylius_channel:
    resources:
        channel:
            classes:
                model: Odiseo\SyliusVendorPlugin\Model\Channel

sylius_product:
    resources:
        product:
            classes:
                model: Odiseo\SyliusVendorPlugin\Model\Product